### ISSUE TITLE
Check plz. For custom currency, balance object output object field value

### ISSUE THREAD

**Issue by gerka** [eternalflow/push-money#3]
when you want to pay of throw the API call  /api/spend/{link_id} 
```
 {
    "option":"transfer-minter","params":{"amount":"
balance->value","to":"MxSome address"}}

```

example 
You want amount balance->value get from  /api/push/{link_id}/balance

```
 {
  "address": "string",
  "balance": {
},     
  "bip_value_total": 0,
  "fiat_rates": {},
  "usd_value_total": 0
}
```

balance->value not correct to take to 

```
 {
    "option":"transfer-minter","params":{"amount":"
balance->value","to":"MxSome address"}}

```

**Comment by qwadratic** [comment]
Fix, debuging and testing was done using mobile phone. 

Hackathon is a challenge!
Task is ordinary? Throw your laptop away and say it again.

**Comment by gerka** [comment]
still can't get max value from respond /api/push/{link_id}/balance 
 balance->value ({"error":"Not enough balance","success":false})

**Comment by qwadratic** [comment]
> still can't get max value from respond /api/push/{link_id}/balance
> balance->value ({"error":"Not enough balance","success":false})

Please write down steps to reproduce the bug
amount, coin, balance response
